# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.CharField(max_length=200)),
                ('relative_url', models.CharField(max_length=50)),
            ],
        ),
    ]
